// This file is auto-generated by generate-image-data.js. Do not edit manually.

export const IMAGE_DATA: { [category: string]: { src: string; alt: string }[] } = {
  "basement-remodeling": [
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-1.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-2.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-3.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-4.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-5.webp",
      "alt": "Basement Remodeling"
    }
  ],
  "bathroom-remodeling": [
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-1.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-10.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-11.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-12.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-13.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-14.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-15.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-16.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-17.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-18.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-19.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-2.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-20.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-21.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-22.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-23.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-24.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-25.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-26.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-3.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-4.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-5.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-6.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-7.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-8.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom-remodeling-9.webp",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom1.png",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom2.png",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom3.png",
      "alt": "Bathroom Remodeling"
    },
    {
      "src": "assets/images/bathroom-remodeling/bathroom4.png",
      "alt": "Bathroom Remodeling"
    }
  ],
  "flooring": [
    {
      "src": "assets/images/flooring/flooring-1.jpg",
      "alt": "Flooring"
    },
    {
      "src": "assets/images/flooring/flooring-2.jpg",
      "alt": "Flooring"
    },
    {
      "src": "assets/images/flooring/flooring-3.jpg",
      "alt": "Flooring"
    },
    {
      "src": "assets/images/flooring/flooring-4.jpg",
      "alt": "Flooring"
    }
  ],
  "kitchen-remodeling": [
    {
      "src": "assets/images/kitchen-remodeling/kitchen-1.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-2.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-3.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-4.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-5.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-6.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-7.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-8.webp",
      "alt": "Kitchen Remodeling"
    }
  ]
};
