// This file is auto-generated by generate-image-data.js. Do not edit manually.

export const IMAGE_DATA: { [category: string]: { src: string; alt: string }[] } = {
  "basement-remodeling": [
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-1.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-2.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-3.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-4.webp",
      "alt": "Basement Remodeling"
    },
    {
      "src": "assets/images/basement-remodeling/basement-remodeling-5.webp",
      "alt": "Basement Remodeling"
    }
  ],
  "flooring": [
    {
      "src": "assets/images/flooring/flooring-1.jpg",
      "alt": "Flooring"
    },
    {
      "src": "assets/images/flooring/flooring-2.jpg",
      "alt": "Flooring"
    },
    {
      "src": "assets/images/flooring/flooring-3.jpg",
      "alt": "Flooring"
    },
    {
      "src": "assets/images/flooring/flooring-4.jpg",
      "alt": "Flooring"
    }
  ],
  "kitchen-remodeling": [
    {
      "src": "assets/images/kitchen-remodeling/kitchen-1.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-2.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-3.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-4.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-5.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-6.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-7.webp",
      "alt": "Kitchen Remodeling"
    },
    {
      "src": "assets/images/kitchen-remodeling/kitchen-8.webp",
      "alt": "Kitchen Remodeling"
    }
  ],
  "general": [
    {
      "src": "assets/images/bathroom1.png",
      "alt": "General Image"
    },
    {
      "src": "assets/images/bathroom2.png",
      "alt": "General Image"
    },
    {
      "src": "assets/images/bathroom3.png",
      "alt": "General Image"
    },
    {
      "src": "assets/images/bathroom4.png",
      "alt": "General Image"
    }
  ]
};
