// This file is auto-generated by generate-image-data.js. Do not edit manually.

export const ALL_IMAGES: { [category: string]: { url: string; alt: string; title: string; description: string }[] } = {
  "basement-remodeling": [
    {
      "url": "assets/images/basement-remodeling/basement-remodeling-1.webp",
      "alt": "Basement Remodeling 1",
      "title": "Basement Remodeling 1",
      "description": "Basement Remodeling project image."
    },
    {
      "url": "assets/images/basement-remodeling/basement-remodeling-2.webp",
      "alt": "Basement Remodeling 2",
      "title": "Basement Remodeling 2",
      "description": "Basement Remodeling project image."
    },
    {
      "url": "assets/images/basement-remodeling/basement-remodeling-3.webp",
      "alt": "Basement Remodeling 3",
      "title": "Basement Remodeling 3",
      "description": "Basement Remodeling project image."
    },
    {
      "url": "assets/images/basement-remodeling/basement-remodeling-4.webp",
      "alt": "Basement Remodeling 4",
      "title": "Basement Remodeling 4",
      "description": "Basement Remodeling project image."
    },
    {
      "url": "assets/images/basement-remodeling/basement-remodeling-5.webp",
      "alt": "Basement Remodeling 5",
      "title": "Basement Remodeling 5",
      "description": "Basement Remodeling project image."
    }
  ],
  "bathroom-remodeling": [
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-1.webp",
      "alt": "Bathroom Remodeling 1",
      "title": "Bathroom Remodeling 1",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-10.webp",
      "alt": "Bathroom Remodeling 10",
      "title": "Bathroom Remodeling 10",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-11.webp",
      "alt": "Bathroom Remodeling 11",
      "title": "Bathroom Remodeling 11",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-12.webp",
      "alt": "Bathroom Remodeling 12",
      "title": "Bathroom Remodeling 12",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-13.webp",
      "alt": "Bathroom Remodeling 13",
      "title": "Bathroom Remodeling 13",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-14.webp",
      "alt": "Bathroom Remodeling 14",
      "title": "Bathroom Remodeling 14",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-15.webp",
      "alt": "Bathroom Remodeling 15",
      "title": "Bathroom Remodeling 15",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-16.webp",
      "alt": "Bathroom Remodeling 16",
      "title": "Bathroom Remodeling 16",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-17.webp",
      "alt": "Bathroom Remodeling 17",
      "title": "Bathroom Remodeling 17",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-18.webp",
      "alt": "Bathroom Remodeling 18",
      "title": "Bathroom Remodeling 18",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-19.webp",
      "alt": "Bathroom Remodeling 19",
      "title": "Bathroom Remodeling 19",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-2.webp",
      "alt": "Bathroom Remodeling 2",
      "title": "Bathroom Remodeling 2",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-20.webp",
      "alt": "Bathroom Remodeling 20",
      "title": "Bathroom Remodeling 20",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-21.webp",
      "alt": "Bathroom Remodeling 21",
      "title": "Bathroom Remodeling 21",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-22.webp",
      "alt": "Bathroom Remodeling 22",
      "title": "Bathroom Remodeling 22",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-23.webp",
      "alt": "Bathroom Remodeling 23",
      "title": "Bathroom Remodeling 23",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-24.webp",
      "alt": "Bathroom Remodeling 24",
      "title": "Bathroom Remodeling 24",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-25.webp",
      "alt": "Bathroom Remodeling 25",
      "title": "Bathroom Remodeling 25",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-26.webp",
      "alt": "Bathroom Remodeling 26",
      "title": "Bathroom Remodeling 26",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-3.webp",
      "alt": "Bathroom Remodeling 3",
      "title": "Bathroom Remodeling 3",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-4.webp",
      "alt": "Bathroom Remodeling 4",
      "title": "Bathroom Remodeling 4",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-5.webp",
      "alt": "Bathroom Remodeling 5",
      "title": "Bathroom Remodeling 5",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-6.webp",
      "alt": "Bathroom Remodeling 6",
      "title": "Bathroom Remodeling 6",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-7.webp",
      "alt": "Bathroom Remodeling 7",
      "title": "Bathroom Remodeling 7",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-8.webp",
      "alt": "Bathroom Remodeling 8",
      "title": "Bathroom Remodeling 8",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom-remodeling-9.webp",
      "alt": "Bathroom Remodeling 9",
      "title": "Bathroom Remodeling 9",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom1.png",
      "alt": "Bathroom1",
      "title": "Bathroom1",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom2.png",
      "alt": "Bathroom2",
      "title": "Bathroom2",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom3.png",
      "alt": "Bathroom3",
      "title": "Bathroom3",
      "description": "Bathroom Remodeling project image."
    },
    {
      "url": "assets/images/bathroom-remodeling/bathroom4.png",
      "alt": "Bathroom4",
      "title": "Bathroom4",
      "description": "Bathroom Remodeling project image."
    }
  ],
  "flooring": [
    {
      "url": "assets/images/flooring/flooring-1.jpg",
      "alt": "Flooring 1",
      "title": "Flooring 1",
      "description": "Flooring project image."
    },
    {
      "url": "assets/images/flooring/flooring-2.jpg",
      "alt": "Flooring 2",
      "title": "Flooring 2",
      "description": "Flooring project image."
    },
    {
      "url": "assets/images/flooring/flooring-3.jpg",
      "alt": "Flooring 3",
      "title": "Flooring 3",
      "description": "Flooring project image."
    },
    {
      "url": "assets/images/flooring/flooring-4.jpg",
      "alt": "Flooring 4",
      "title": "Flooring 4",
      "description": "Flooring project image."
    }
  ],
  "kitchen-remodeling": [
    {
      "url": "assets/images/kitchen-remodeling/kitchen-1.webp",
      "alt": "Kitchen 1",
      "title": "Kitchen 1",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-10.png",
      "alt": "Kitchen 10",
      "title": "Kitchen 10",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-11.jpg",
      "alt": "Kitchen 11",
      "title": "Kitchen 11",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-2.webp",
      "alt": "Kitchen 2",
      "title": "Kitchen 2",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-3.webp",
      "alt": "Kitchen 3",
      "title": "Kitchen 3",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-4.webp",
      "alt": "Kitchen 4",
      "title": "Kitchen 4",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-5.webp",
      "alt": "Kitchen 5",
      "title": "Kitchen 5",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-6.webp",
      "alt": "Kitchen 6",
      "title": "Kitchen 6",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-7.webp",
      "alt": "Kitchen 7",
      "title": "Kitchen 7",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-8.webp",
      "alt": "Kitchen 8",
      "title": "Kitchen 8",
      "description": "Kitchen Remodeling project image."
    },
    {
      "url": "assets/images/kitchen-remodeling/kitchen-9.png",
      "alt": "Kitchen 9",
      "title": "Kitchen 9",
      "description": "Kitchen Remodeling project image."
    }
  ]
};
